package com.taotao.mapper;

import com.taotao.pojo.ContentCategory;

public interface ContentCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content_category
     *
     * @mbggenerated Thu Apr 14 13:30:03 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content_category
     *
     * @mbggenerated Thu Apr 14 13:30:03 CST 2016
     */
    int insert(ContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content_category
     *
     * @mbggenerated Thu Apr 14 13:30:03 CST 2016
     */
    int insertSelective(ContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content_category
     *
     * @mbggenerated Thu Apr 14 13:30:03 CST 2016
     */
    ContentCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content_category
     *
     * @mbggenerated Thu Apr 14 13:30:03 CST 2016
     */
    int updateByPrimaryKeySelective(ContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content_category
     *
     * @mbggenerated Thu Apr 14 13:30:03 CST 2016
     */
    int updateByPrimaryKey(ContentCategory record);
}